version: "3.7"

# docker-compose build && docker-compose up

services:
  web:
    build: .
    depends_on:
        - db
        - solr
        - redis
    ports:
        - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./ckan.ini:/ckan.ini
      - ckan-filestore:/var/lib/ckan/default

  datapusher:
    build: contrib/ckan-datapusher
  
  db:
    image: postgres:9.6
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=ckan_default
      - POSTGRES_PASSWORD=pass
      - PGUSER=ckan_default
      - PGPASSWORD=pass
      - POSTGRES_ADD_DATABASES=datastore_default:datastore_default
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./contrib/postgres:/docker-entrypoint-initdb.d
  
  solr:
    image: codeforafrica/ckan-solr:2.7
    ports:
        - "8983:8983"
    volumes:
      - solr-data:/opt/solr/server/solr/ckan

  redis:
    image: redis:latest
  

volumes:
  postgres-data: {}
  solr-data: {}
  ckan-filestore: {}
